#generated by $ rails generate clearance:install

Clearance.configure do |config|
  config.routes = false #disable Clearance routes and take full control over routing and URL design. This ensures that your app's URL design won't be affected if the gem's routes and URL design are changed.
  config.mailer_sender = "reply@example.com" #reset password, email from
  config.rotate_csrf_on_sign_in = true
  #csrf cross server request forgery
  #set rotate_csrf_on_sign_in to true, to avoid session fixation attacks
end
