# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

FACEBOOK_APP_KEY: '1362965383750336'  #Note the use of the single quotes ' ' here. 
FACEBOOK_APP_SECRET: '51c8ad97bbfc821ee00997b69ef0cf2f'


AWS_ACCESS_KEY_ID: 'AKIAISBOJCJ36AIWQE7Q'
AWS_SECRET_ACCESS_KEY: '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'
AWS_REGION: 'ap-southeast-1'
AWS_S3_BUCKET: 'pairbnb-will'


BRAINTREE_MERCHANT_ID: '8vx2yjzyvr4dcdgg'
BRAINTREE_PUBLIC_KEY: 'dsjtpfp2zpfwtkvk'
BRAINTREE_PRIVATE_KEY: '61d6d49a882211c7ac90b7c4a9f9f3b3'


GMAIL_USERNAME: ''
GMAIL_PASSWORD: ''


