class ApplicationController < ActionController::Base
	include Clearance::Controller  #generated by $ rails generate clearance:install
	protect_from_forgery with: :exception  
	#includes by default in application_controller.rb by rails, protect from csrf by inserting auth token in form submission
	#:with - Set the method to handle unverified request.
	#:exception - Raises ActionController::InvalidAuthenticityToken exception.
end
